id: P006864
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ1068
  title: མགོན་པོའི་མན་ངག་ཤོག་དྲིལ་རྣམས་ཀྱི་ཟུར་འདེབས་ཞལ་ཤེས་དང་བཅས་པ
  author: ''
  volumes:
    33a3049573074b52a673c967db62636a:
      image_group_id: I1CZ1427
      title: ''
      volume_number: 1
      total_pages: 14
      base_file: v001.txt
